[package]
name = "keyforge-adapter"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description.workspace = true
repository.workspace = true
lints.workspace = true

[dependencies]
keyforge-model = { path = "../keyforge-model" }
keyforge-protocol = { path = "../keyforge-protocol" }
thiserror = "2.0"
