// apps/keyforge-ui/src/api/constants.ts

import { Config } from "../types";

export const DEFAULT_APP_CONFIG: Config = {
    search: {
        search_epochs: 10000,
        search_steps: 100000,
        search_patience: 500,
        search_patience_threshold: 0.1,
        temp_min: 0.005,
        temp_max: 20.0,
        opt_limit_fast: 100,
        opt_limit_slow: 1500,
        reheats: 3,
        reheat_factor: 0.5,
        include_thumbs: true,
    },
    weights: {
        penalty_sfr_weak_finger: 20.0,
        penalty_sfr_bad_row: 25.0,
        penalty_sfr_lat: 40.0,
        penalty_sfb_lateral: 65.0,
        penalty_sfb_lateral_weak: 160.0,
        penalty_sfb_base: 400.0,
        penalty_sfb_outward_adder: 10.0,
        penalty_sfb_diagonal: 240.0,
        penalty_sfb_long: 280.0,
        penalty_sfb_bottom: 45.0,
        weight_weak_finger_sfb: 2.7,
        threshold_sfb_long_row_diff: 2,
        threshold_scissor_row_diff: 2,
        threshold_reach_stretch: 1.2,
        penalty_scissor: 25.0,
        penalty_ring_pinky: 1.3,
        penalty_lateral: 50.0,
        penalty_monogram_stretch: 20.0,
        penalty_skip: 20.0,
        penalty_redirect: 65.0,
        penalty_hand_run: 5.0,
        bonus_inward_roll: 40.0,
        bonus_bigram_roll_in: 35.0,
        bonus_bigram_roll_out: 25.0,
        penalty_high_in_med: 12.0,
        penalty_high_in_low: 20.0,
        penalty_med_in_prime: 2.0,
        penalty_med_in_low: 2.0,
        penalty_low_in_prime: 15.0,
        penalty_low_in_med: 2.0,
        penalty_imbalance: 200.0,
        max_hand_imbalance: 0.55,
        weight_vertical_travel: 1.0,
        weight_lateral_travel: 3.5,
        weight_finger_effort: 2.2,
        default_cost_ms: 120.0,
        loader_trigram_limit: 3000,
        trigram_coverage: 0.99,
        finger_penalty_scale: [1.0, 1.0, 1.1, 1.3, 1.6],
        comfortable_scissors: "21,23,34",
    },
    defs: {
        tier_high_chars: "etaoinshr",
        tier_med_chars: "ldcumwfgypb.,",
        tier_low_chars: "vkjxqz/;",
        critical_bigrams: "th,he,in,er,an,re,nd,ou",
        finger_repeat_scale: [1.0, 1.0, 1.0, 1.2, 1.5],
    },
    pinned_keys: [],
};
