[package]
name = "keyforge-security"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description = "Security, authentication, and cryptographic utilities for secure KeyForge network communications."
repository.workspace = true
[lints]
workspace = true

[dependencies]
keyforge-testing-macros.workspace = true
zeroize.workspace = true
subtle.workspace = true
ed25519-dalek.workspace = true
rand.workspace = true
hex.workspace = true
sha2.workspace = true
pasetors.workspace = true
rsa.workspace = true
thiserror.workspace = true
keyforge-model = { path = "../keyforge-model" }
chrono.workspace = true