[package]
name = "keyforge-security"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description = "Security, authentication, and cryptographic utilities for secure KeyForge network communications."
repository.workspace = true
[lints]
workspace = true

[dependencies]
zeroize.workspace = true
subtle = "2.6"
ed25519-dalek.workspace = true
rand.workspace = true
hex.workspace = true
sha2.workspace = true
pasetors = { version = "0.7", features = ["v4"] }
thiserror.workspace = true
keyforge-model = { path = "../keyforge-model" }