// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricViolation } from "./MetricViolation";

export type AnalysisReport = { score: number, distance: number, sfb_total: number, sfb_ratio: number, hand_balance: number, scissors: number, redirects: number, rolls: number, heatmap: Array<number>, top_sfbs: Array<MetricViolation>, top_scissors: Array<MetricViolation>, top_redirs: Array<MetricViolation>, };
