// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutDefinitions } from "./LayoutDefinitions";
import type { ScoringWeights } from "./ScoringWeights";
import type { SearchParams } from "./SearchParams";

export type Config = { search: SearchParams, weights: ScoringWeights, defs: LayoutDefinitions, };
