// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier for a finger (Thumb=0 to Pinky=4).
 */
export type FingerIndex = number;
