// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BiometricSample } from "./BiometricSample";
import type { CorpusSource } from "./CorpusSource";
import type { CostMatrixSource } from "./CostMatrixSource";
import type { KeyConstraint } from "./KeyConstraint";
import type { KeyboardDefinition } from "./KeyboardDefinition";
import type { ScoringWeights } from "./ScoringWeights";
import type { SearchParams } from "./SearchParams";

/**
 * Full configuration for a running job.
 */
export type JobConfig = { 
/**
 * Keyboard geometry definition.
 */
definition: KeyboardDefinition, 
/**
 * Scoring weights.
 */
weights: ScoringWeights, 
/**
 * Search parameters.
 */
params: SearchParams, 
/**
 * Keys pinned to specific positions.
 */
pinned_keys: Array<KeyConstraint>, 
/**
 * Text corpora to use.
 */
corpora: Array<CorpusSource>, 
/**
 * Cost matrix source.
 */
cost_matrix: CostMatrixSource, 
/**
 * User biometric data.
 */
biometrics: Array<BiometricSample>, 
/**
 * Parent job ID.
 */
parent_job_id: string | null, 
/**
 * Baseline score.
 */
baseline_score: number | null, 
/**
 * Parent job IDs.
 */
parents: Array<string>, };
