// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BiometricSample } from "./BiometricSample";
import type { CorpusSource } from "./CorpusSource";
import type { CostMatrixSource } from "./CostMatrixSource";
import type { KeyConstraint } from "./KeyConstraint";
import type { KeyboardDefinition } from "./KeyboardDefinition";
import type { ScoringWeights } from "./ScoringWeights";
import type { SearchParams } from "./SearchParams";

export type JobRequest = { version: number, definition: KeyboardDefinition, weights: ScoringWeights, params: SearchParams, pinned_keys: Array<KeyConstraint>, corpora: Array<CorpusSource>, cost_matrix: CostMatrixSource, biometrics: Array<BiometricSample>, parent_job_id: string | null, baseline_score: number | null, parents: Array<string>, };
