// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobStatus = { job_id: string, status: string, active_nodes: number, best_score: number | null, best_layout: string | null, total_samples: number, };
