// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyboardMeta = { name: string, author: string, version: string, notes: string, type: string, };
