// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyboardGeometry } from "./KeyboardGeometry";
import type { KeyboardMeta } from "./KeyboardMeta";

export type KeyboardDefinition = { meta: KeyboardMeta, geometry: KeyboardGeometry, layouts: { [key in string]?: string }, };
