// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyCode } from "./KeyCode";
import type { KeycodeDefinition } from "./KeycodeDefinition";

export type KeycodeRegistry = { definitions: Array<KeycodeDefinition>, name_to_code: { [key in string]?: KeyCode }, code_to_label: { [key in KeyCode]?: string }, };
