// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical index of a physical key in the keyboard array.
 */
export type KeyIndex = number;
