// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResultSubmission = { version: number, job_id: string, layout: string, score: number, timestamp: bigint, nonce: bigint, node_id: string, signature: string | null, };
