// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Submission of a result from a worker.
 */
export type ResultSubmission = { 
/**
 * Protocol version.
 */
version: number, 
/**
 * The Job ID.
 */
job_id: string, 
/**
 * The layout string.
 */
layout: string, 
/**
 * The score achieved.
 */
score: number, 
/**
 * Timestamp of the result.
 */
timestamp: bigint, 
/**
 * Nonce for cryptographic verification.
 */
nonce: bigint, 
/**
 * The Node ID of the worker.
 */
node_id: string, 
/**
 * Cryptographic signature.
 */
signature: string | null, };
