// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SwapSuggestion = { index_a: number, index_b: number, key_a: string, key_b: string, score_delta: number, improvement_pct: number, };
