// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TuningProfile = { strategy: string, batch_size: number, thread_count: number, };
