DROP VIEW IF EXISTS v_job_lineage;
ALTER TABLE jobs DROP COLUMN IF EXISTS owner_id;
ALTER TABLE jobs DROP COLUMN IF EXISTS priority;
ALTER TABLE jobs DROP COLUMN IF EXISTS parent_job_id;
DROP TABLE IF EXISTS audit_logs;
