[package]
name = "keyforge-wasm"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description.workspace = true
repository.workspace = true
lints.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
keyforge-adapter = { path = "../../libs/keyforge-adapter" }
wasm-bindgen = "0.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1"

keyforge-protocol = { path = "../../libs/keyforge-protocol" }
keyforge-model = { path = "../../libs/keyforge-model" }
keyforge-compute = { path = "../../libs/keyforge-compute", default-features = false, features = [
    "single_threaded",
] }
keyforge-core = { path = "../../libs/keyforge-core" }
async-trait = "0.1"
wasm-bindgen-futures = "0.4"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
