// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricViolation } from "./MetricViolation";

/**
 * Detailed breakdown of a layout's performance.
 */
export type AnalysisReport = { 
/**
 * Total weighted score (lower is better).
 */
score: number, 
/**
 * Total finger travel distance.
 */
distance: number, 
/**
 * Total Same Finger Bigram cost.
 */
sfb_total: number, 
/**
 * Ratio of SFBs to total bigrams.
 */
sfb_ratio: number, 
/**
 * Hand balance (-1.0 Left, +1.0 Right, 0.0 Balanced).
 */
hand_balance: number, 
/**
 * Scissor (adjacent finger stretch) score.
 */
scissors: number, 
/**
 * Redirect (direction change) score.
 */
redirects: number, 
/**
 * Inward roll score.
 */
rolls: number, 
/**
 * Per-key usage heatmap.
 */
heatmap: Array<number>, 
/**
 * Top SFB offenders.
 */
top_sfbs: Array<MetricViolation>, 
/**
 * Top Scissor offenders.
 */
top_scissors: Array<MetricViolation>, 
/**
 * Top Redirect offenders.
 */
top_redirs: Array<MetricViolation>, };
