// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Column index.
 *
 * Positive values are typically to the right, negative to the left, 
 * with 0 being a reference column (e.g., center or pinky column).
 */
export type ColIndex = number;
