// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutDefinitions } from "./LayoutDefinitions";
import type { ScoringWeights } from "./ScoringWeights";
import type { SearchParams } from "./SearchParams";

/**
 * The root configuration aggregate for a KeyForge session.
 */
export type Config = { 
/**
 * Parameters controlling the annealing search process.
 */
search: SearchParams, 
/**
 * Weights and penalties for the scoring engine.
 */
weights: ScoringWeights, 
/**
 * Definitions for layout generation (character tiers, etc.).
 */
defs: LayoutDefinitions, };
