// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines a source for text corpus data.
 */
export type CorpusSource = { 
/**
 * The identifier or filename of the corpus (e.g., "text/en_std").
 */
id: string, 
/**
 * The weight multiplier for this corpus (default: 1.0).
 */
weight: number, 
/**
 * Optional hash for integrity verification.
 */
hash: string | null, };
