// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the source of the cost matrix used for scoring.
 */
export type CostMatrixSource = { "type": "Predefined", "data": string } | { "type": "Custom", "data": string };
