// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the finger (Thumb=0, Index=1, Middle=2, Ring=3, Pinky=4).
 */
export type FingerIndex = number;
