// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for a specific optimization job configuration.
 * Generated by hashing the canonical representation of all inputs.
 */
export type JobIdentifier = { 
/**
 * The hex-encoded SHA-256 hash.
 */
hash: string, };
