// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Errors that can occur during Job ID generation.
 */
export type JobIdError = { "Serialize": string };
