// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsable key action from an external format.
 */
export type KeyAction = { "Simple": string } | "Transparent" | "NoOp" | { "LayerMomentary": number } | { "LayerToggle": number } | { "LayerOn": number } | { "ModTap": { 
/**
 * The modifier (e.g., "LSHIFT").
 */
mod_name: string, 
/**
 * The tap key (recursive).
 */
key: KeyAction, } } | { "LayerTap": { 
/**
 * The layer index.
 */
layer: number, 
/**
 * The tap key (recursive).
 */
key: KeyAction, } } | { "StickyMod": string } | "CapsWord" | { "Raw": string };
