// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a parsed action from a keymap file (e.g., QMK/ZMK format).
 */
export type KeyAction = { "Simple": string } | "Transparent" | "NoOp" | { "LayerMomentary": number } | { "LayerToggle": number } | { "LayerOn": number } | { "ModTap": { 
/**
 * The modifier (e.g., "LSHIFT").
 */
mod_name: string, 
/**
 * The tap key (e.g., "KC_A").
 */
key: string, } } | { "LayerTap": { 
/**
 * The layer index.
 */
layer: number, 
/**
 * The tap key.
 */
key: string, } } | { "StickyMod": string } | "CapsWord" | { "Raw": string };
