// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata describing a keyboard definition.
 */
export type KeyboardMeta = { 
/**
 * Display name of the keyboard.
 */
name: string, 
/**
 * Author of the definition.
 */
author: string, 
/**
 * Version string.
 */
version: string, 
/**
 * Additional notes or description.
 */
notes: string, 
/**
 * Type of keyboard (e.g., "split", "ortho").
 */
type: string, };
