// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyIndex } from "./KeyIndex";

/**
 * A constraint pinning a specific key to a specific physical index.
 */
export type KeyConstraint = { 
/**
 * The physical index to pin.
 */
index: KeyIndex, 
/**
 * The key label to pin (e.g., "A", "Shift").
 */
key: string, };
