// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyCode } from "./KeyCode";
import type { KeycodeDefinition } from "./KeycodeDefinition";

/**
 * Registry for looking up key codes by name or ID.
 */
export type KeycodeRegistry = { 
/**
 * List of all definitions.
 */
definitions: Array<KeycodeDefinition>, name_to_code: { [key in string]?: KeyCode }, code_to_label: { [key in KeyCode]?: string }, };
