// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definitions for character tiers and critical bigrams.
 */
export type LayoutDefinitions = { 
/**
 * Characters considered high priority.
 */
tier_high_chars: string, 
/**
 * Characters considered medium priority.
 */
tier_med_chars: string, 
/**
 * Characters considered low priority.
 */
tier_low_chars: string, 
/**
 * Bigrams that must be optimized for.
 */
critical_bigrams: string, 
/**
 * Scale factors for finger repeat penalties.
 */
finger_repeat_scale: string, };
