// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Errors related to core model logic and integrity.
 */
export type ModelError = { "Serialization": string };
