// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Row index.
 *
 * Typically: Home=0, Top<0, Bottom>0.
 */
export type RowIndex = number;
