// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fixed-point score representation.
 * Internally stored as `i64` scaled by `SCORE_SCALE` (1,000,000).
 */
export type Score = number;
