// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weights and penalties defining the "personality" of the scoring engine.
 */
export type ScoringWeights = { 
/**
 * Penalty for Same Finger Repeat on a weak finger.
 */
penalty_sfr_weak_finger: number, 
/**
 * Penalty for Same Finger Repeat involving a bad row jump.
 */
penalty_sfr_bad_row: number, 
/**
 * Penalty for lateral Same Finger Repeat.
 */
penalty_sfr_lat: number, 
/**
 * Penalty for lateral Same Finger Bigram.
 */
penalty_sfb_lateral: number, 
/**
 * Penalty for lateral SFB on a weak finger.
 */
penalty_sfb_lateral_weak: number, 
/**
 * Base penalty for any Same Finger Bigram.
 */
penalty_sfb_base: number, 
/**
 * Additional penalty for outward rolling SFBs.
 */
penalty_sfb_outward_adder: number, 
/**
 * Penalty for diagonal SFBs.
 */
penalty_sfb_diagonal: number, 
/**
 * Penalty for long-distance SFBs.
 */
penalty_sfb_long: number, 
/**
 * Penalty for bottom-row SFBs.
 */
penalty_sfb_bottom: number, 
/**
 * Multiplier for SFBs on weak fingers.
 */
weight_weak_finger_sfb: number, 
/**
 * Row difference threshold for "long" SFBs.
 */
threshold_sfb_long_row_diff: number, 
/**
 * Row difference threshold for scissors.
 */
threshold_scissor_row_diff: number, 
/**
 * Distance threshold for reach stretches.
 */
threshold_reach_stretch: number, 
/**
 * Penalty for scissor (adjacent finger stretch) movements.
 */
penalty_scissor: number, 
/**
 * Penalty for ring-pinky interactions.
 */
penalty_ring_pinky: number, 
/**
 * Penalty for lateral movement.
 */
penalty_lateral: number, 
/**
 * Penalty for single-key stretches.
 */
penalty_monogram_stretch: number, 
/**
 * Penalty for skipping a key (hurdle).
 */
penalty_skip: number, 
/**
 * Penalty for redirecting flow (e.g., Left -> Right -> Left).
 */
penalty_redirect: number, 
/**
 * Penalty for excessive hand alternation runs.
 */
penalty_hand_run: number, 
/**
 * Bonus (negative cost) for inward rolls.
 */
bonus_inward_roll: number, 
/**
 * Bonus for specific bigram inward rolls.
 */
bonus_bigram_roll_in: number, 
/**
 * Bonus for specific bigram outward rolls.
 */
bonus_bigram_roll_out: number, 
/**
 * Penalty for high-frequency keys in medium slots.
 */
penalty_high_in_med: number, 
/**
 * Penalty for high-frequency keys in low slots.
 */
penalty_high_in_low: number, 
/**
 * Penalty for medium-frequency keys in prime slots.
 */
penalty_med_in_prime: number, 
/**
 * Penalty for medium-frequency keys in low slots.
 */
penalty_med_in_low: number, 
/**
 * Penalty for low-frequency keys in prime slots.
 */
penalty_low_in_prime: number, 
/**
 * Penalty for low-frequency keys in medium slots.
 */
penalty_low_in_med: number, 
/**
 * Penalty for hand imbalance.
 */
penalty_imbalance: number, 
/**
 * Maximum allowed hand imbalance ratio.
 */
max_hand_imbalance: number, 
/**
 * Weight multiplier for vertical travel distance.
 */
weight_vertical_travel: number, 
/**
 * Weight multiplier for lateral travel distance.
 */
weight_lateral_travel: number, 
/**
 * Weight multiplier for finger effort.
 */
weight_finger_effort: number, 
/**
 * Default cost in milliseconds (if using time-based scoring).
 */
default_cost_ms: number, 
/**
 * Limit on the number of trigrams to load.
 */
loader_trigram_limit: number, 
/**
 * Required trigram coverage (0.0 - 1.0).
 */
trigram_coverage: number, 
/**
 * Comma-separated string of finger penalty multipliers.
 */
finger_penalty_scale: string, 
/**
 * Comma-separated string of comfortable scissor pairs.
 */
comfortable_scissors: string, };
