// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weights and penalties defining the "personality" of the scoring engine.
 */
export type ScoringWeights = { 
/**
 * Finger penalty multipliers (Thumb, Index, Middle, Ring, Pinky).
 */
finger_penalty_scale: [number, number, number, number, number], 
/**
 * Comma-separated list of comfortable scissor pairs.
 */
comfortable_scissors: string, } & ({ [key in string]?: number });
