// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preference for which hand should handle Space keys.
 */
export type SpaceHandPreference = "left" | "right" | "bilateral";
