[package]
name = "keyforge-export"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description = "Extensible export engine for generating specialized keyboard layout configuration files and assets."
repository.workspace = true
[lints]
workspace = true

[dependencies]
keyforge-testing-macros.workspace = true
keyforge-model = { path = "../keyforge-model" }
keyforge-protocol = { path = "../keyforge-protocol" }
keyforge-adapter = { path = "../keyforge-adapter" }
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
keyforge-testing = { path = "../keyforge-testing" }
proptest.workspace = true
