[package]
name = "keyforge-testing"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description = "Hermetic test harness and fixtures for integration testing."
repository.workspace = true
[lints]
workspace = true

[dependencies]
keyforge-testing-macros.workspace = true
keyforge-compute = { path = "../keyforge-compute" }
keyforge-infra = { path = "../keyforge-infra" }
keyforge-model = { path = "../keyforge-model" }
keyforge-protocol = { path = "../keyforge-protocol" }
tempfile.workspace = true
serde_json.workspace = true
tokio.workspace = true
anyhow.workspace = true
