[package]
name = "keyforge-testing"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description = "Utility library providing hermetic workspaces and test fixtures for the KeyForge ecosystem."
repository.workspace = true
[lints]
workspace = true

[dependencies]
keyforge-protocol = { path = "../keyforge-protocol" }
keyforge-model = { path = "../keyforge-model" }
keyforge-core = { path = "../keyforge-core" }
serde_json = "1.0"
tempfile = "3.24"
