// libs/keyforge-model/src/job.rs

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Job identification and hashing logic.
//!
//! This module provides the `JobIdentifier` used to uniquely identify
//! a specific optimization task based on its configuration.

use crate::config::{CostMatrixSource, KeyConstraint, ScoringWeights, SearchParams};
use crate::geometry::KeyboardGeometry;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
#[cfg(feature = "ts_bindings")]
use ts_rs::TS;
use utoipa::ToSchema;

/// Unique identifier for a specific optimization job configuration.
/// Generated by hashing the canonical representation of all inputs.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[cfg_attr(feature = "ts_bindings", derive(TS), ts(export))]
pub struct JobIdentifier {
    /// The hex-encoded SHA-256 hash.
    pub hash: String,
}

use crate::error::ModelError;

impl JobIdentifier {
    /// Attempts to generate a Job ID from the constituent parts.
    ///
    /// # Errors
    ///
    /// Returns a `ModelError` if any of the parts cannot be serialized or
    /// if the configuration is invalid.
    pub fn try_from_parts(
        geometry: &KeyboardGeometry,
        weights: &ScoringWeights,
        params: &SearchParams,
        pinned_keys: &[KeyConstraint],
        corpus_name: &str,
        cost_matrix: &CostMatrixSource,
    ) -> Result<Self, ModelError> {
        fn feed<T: Serialize>(hasher: &mut Sha256, value: &T) -> Result<(), ModelError> {
            // Use serde_json::to_value -> to_vec for deterministic canonicalization.
            // to_value converts structs/maps to a BTreeMap-backed Value, ensuring sorted keys.
            let canonical = serde_json::to_value(value)
                .map_err(|e| ModelError::Serialization(e.to_string()))?;

            let bytes = serde_json::to_vec(&canonical)
                .map_err(|e| ModelError::Serialization(e.to_string()))?;

            hasher.update((bytes.len() as u64).to_le_bytes());
            hasher.update(&bytes);
            Ok(())
        }

        let mut hasher = Sha256::new();

        feed(&mut hasher, geometry)?;
        feed(&mut hasher, weights)?;
        feed(&mut hasher, params)?;

        // Sort pins for canonicalization
        let mut sorted_pins = pinned_keys.to_vec();
        sorted_pins.sort_by(|a, b| a.index.cmp(&b.index));
        feed(&mut hasher, &sorted_pins)?;

        hasher.update((corpus_name.len() as u64).to_le_bytes());
        hasher.update(corpus_name.as_bytes());

        match cost_matrix {
            CostMatrixSource::Predefined(s) => {
                hasher.update(b"PRE");
                hasher.update(s.as_bytes());
            }
        }

        let result = hasher.finalize();
        Ok(Self {
            hash: hex::encode(result),
        })
    }

    /// Generates a Job ID, returning a Result.
    /// This replaces the panicking `from_parts` method.
    ///
    /// # Errors
    ///
    /// Returns a `ModelError` if any of the constituent parts fail validation
    /// or serialization.
    pub fn from_parts(
        geometry: &KeyboardGeometry,
        weights: &ScoringWeights,
        params: &SearchParams,
        pinned_keys: &[KeyConstraint],
        corpus_name: &str,
        cost_matrix: &CostMatrixSource,
    ) -> Result<Self, ModelError> {
        Self::try_from_parts(
            geometry,
            weights,
            params,
            pinned_keys,
            corpus_name,
            cost_matrix,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::KeyIndex;

    #[test]
    fn test_job_id_determinism() {
        let geo = KeyboardGeometry::default();
        let weights = ScoringWeights::default();
        let params = SearchParams::default();
        let pins = vec![KeyConstraint {
            index: KeyIndex(0),
            key: "A".into(),
        }];

        let id1 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &pins,
            "en",
            &CostMatrixSource::default(),
        )
        .unwrap();
        let id2 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &pins,
            "en",
            &CostMatrixSource::default(),
        )
        .unwrap();

        assert_eq!(id1.hash, id2.hash);
    }

    #[test]
    fn test_job_id_pin_sorting_determinism() {
        let geo = KeyboardGeometry::default();
        let weights = ScoringWeights::default();
        let params = SearchParams::default();

        let pin_a = KeyConstraint {
            index: KeyIndex(0),
            key: "A".into(),
        };
        let pin_b = KeyConstraint {
            index: KeyIndex(1),
            key: "B".into(),
        };

        let id1 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &[pin_a.clone(), pin_b.clone()],
            "en",
            &CostMatrixSource::default(),
        )
        .unwrap();
        let id2 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &[pin_b, pin_a],
            "en",
            &CostMatrixSource::default(),
        )
        .unwrap();

        assert_eq!(
            id1.hash, id2.hash,
            "Hash must be same regardless of pin order"
        );
    }
}
