// libs/keyforge-model/src/job.rs

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Job identification and hashing logic.
//!
//! This module provides the `JobIdentifier` used to uniquely identify
//! a specific optimization task based on its configuration.

use sha2::{Digest, Sha256};

use crate::config::CorpusSource;

/// Generates a deterministic hash for a set of corpora sources, incorporating content hashes if present.
#[must_use]
pub fn calculate_corpora_hash(sources: &[CorpusSource]) -> String {
    // 1. Sort by ID for canonicalization
    let mut sorted = sources.to_vec();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));

    // 2. Hash the sorted list deterministically
    let mut hasher = Sha256::new();
    for s in &sorted {
        hasher.update(s.id.as_bytes());
        // Use separator to prevent concatenation collisions
        hasher.update([0xFF]);
<<<<<<< HEAD
        
=======

>>>>>>> master
        // Hash weight bits for strict equality
        hasher.update(s.weight.to_bits().to_be_bytes());
        hasher.update([0xFF]);

        // Incorporate hash field if present
        if let Some(h) = &s.hash {
            hasher.update([0x01]); // Marker for Some
            hasher.update(h.as_bytes());
        } else {
            hasher.update([0x00]); // Marker for None
        }
        hasher.update([0xFF]); // End of item separator
    }
<<<<<<< HEAD
    
=======

>>>>>>> master
    hex::encode(hasher.finalize())
}

/// Unique identifier for a specific optimization job configuration.
/// Generated by hashing the canonical representation of all inputs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct JobIdentifier {
    /// The hex-encoded SHA-256 hash.
    pub hash: String,
}

/// Marker trait for Job states.
pub trait JobState: std::fmt::Debug + Clone {}

/// Job is in the queue, awaiting a worker.
#[derive(Debug, Clone)]
pub struct Pending;
impl JobState for Pending {}

/// Job is currently being processed by one or more workers.
#[derive(Debug, Clone)]
pub struct Running {
    /// Number of active worker nodes.
    pub active_nodes: usize,
    /// Best score found so far.
    pub current_best: Option<crate::types::Score>,
}
impl JobState for Running {}

/// Job has been finished or timed out.
#[derive(Debug, Clone)]
pub struct Completed {
    /// Final best score achieved.
    pub final_score: crate::types::Score,
    /// Final optimized layout.
    pub final_layout: crate::layout::Layout,
    /// Total compute time across all nodes (seconds).
    pub total_compute_sec: u64,
}
impl JobState for Completed {}

/// A reified Optimization Job, following the Typestate Pattern.
#[derive(Debug, Clone)]
pub struct Job<S: JobState> {
    /// Canonical identifier.
    pub id: JobIdentifier,
    /// Current state data.
    pub state: S,
}

/// Unified Enum for Job Status (used in protocols and persistence).
///
/// # Examples
///
/// ```
/// use keyforge_model::{JobStatus, Running, Score};
/// let status = JobStatus::Running(Running {
///     active_nodes: 5,
///     current_best: Some(Score::from_scaled_i64(100)),
/// });
/// ```
#[derive(Debug, Clone)]
pub enum JobStatus {
    /// Job is awaiting workers.
    Pending(Pending),
    /// Job is active.
    Running(Running),
    /// Job is finished.
    Completed(Completed),
}

impl JobIdentifier {
    /// Creates a new `JobIdentifier` from a pre-calculated hash.
    #[must_use]
    pub fn new(hash: impl Into<String>) -> Self {
        Self { hash: hash.into() }
    }

    /// Deterministically calculates a unique `JobIdentifier` from all configuration inputs.
    ///
    /// The inputs provided here MUST be the content-resolved domain objects
    /// to ensure full reproducibility and cache integrity.
    #[must_use]
    pub fn calculate(
        keyboard: &crate::geometry::KeyboardGeometry,
        corpora: &[crate::config::CorpusSource],
        weights: &crate::config::ScoringWeights,
        params: &crate::config::SearchParams,
        cost_matrix: &crate::config::CostMatrixSource,
        pinned_keys: &[crate::config::KeyConstraint],
    ) -> Self {
        let mut hasher = Sha256::new();

        // 1. Keyboard Geometry
        hasher.update(keyboard.calculate_hash().as_bytes());
        hasher.update([0xFF]);

        // 2. Corpora (Content-Addressable)
        hasher.update(calculate_corpora_hash(corpora).as_bytes());
        hasher.update([0xFF]);

        // 3. Scoring Weights
        hasher.update(weights.calculate_hash().as_bytes());
        hasher.update([0xFF]);

        // 4. Search Params
        hasher.update(params.calculate_hash().as_bytes());
        hasher.update([0xFF]);

        // 5. Cost Matrix Source
        hasher.update(cost_matrix.calculate_hash().as_bytes());
        hasher.update([0xFF]);

        // 6. Pinned Keys
        for constraint in pinned_keys {
            hasher.update(constraint.calculate_hash().as_bytes());
        }

        Self {
            hash: hex::encode(hasher.finalize()),
        }
    }
}

#[keyforge_testing_macros::kf_test]
mod tests {
    use super::*;
    use crate::types::KeyIndex;

    #[test]
<<<<<<< HEAD
    fn test_job_id_determinism() {
        let geo = KeyboardGeometry::default();
        let weights = ScoringWeights::default();
        let params = SearchParams::default();
        let pins = vec![KeyConstraint {
            index: KeyIndex::new(0),
            key: "A".into(),
=======
    fn test_calculate_corpora_hash_content_addressing() -> anyhow::Result<()> {
        let s1 = vec![CorpusSource {
            id: "a".into(),
            weight: 1.0,
            hash: Some("hash1".into()),
>>>>>>> master
        }];
        let s2 = vec![CorpusSource {
            id: "a".into(),
            weight: 1.0,
            hash: Some("hash2".into()),
        }];
        assert_ne!(calculate_corpora_hash(&s1), calculate_corpora_hash(&s2));

<<<<<<< HEAD
        let id1 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &pins,
            "en",
            &CostMatrixSource::default(),
        )
        .unwrap();
        let id2 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &pins,
            "en",
            &CostMatrixSource::default(),
        )
        .unwrap();

        assert_eq!(id1.hash, id2.hash);
    }

    #[test]
    fn test_job_id_pin_sorting_determinism() {
        let geo = KeyboardGeometry::default();
        let weights = ScoringWeights::default();
        let params = SearchParams::default();

        let pin_a = KeyConstraint {
            index: KeyIndex::new(0),
            key: "A".into(),
        };
        let pin_b = KeyConstraint {
            index: KeyIndex::new(1),
            key: "B".into(),
        };

        let id1 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &[pin_a.clone(), pin_b.clone()],
            "en",
            &CostMatrixSource::default(),
        )
        .unwrap();
        let id2 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &[pin_b, pin_a],
            "en",
            &CostMatrixSource::default(),
        )
        .unwrap();

        assert_eq!(
            id1.hash, id2.hash,
            "Hash must be same regardless of pin order"
        );
    }

    #[test]
    fn test_calculate_corpora_fingerprint_content_addressing() {
        let s1 = vec![CorpusSource {
            id: "a".into(),
            weight: 1.0,
            hash: Some("hash1".into()),
        }];
        let s2 = vec![CorpusSource {
            id: "a".into(),
            weight: 1.0,
            hash: Some("hash2".into()),
        }];
        assert_ne!(calculate_corpora_fingerprint(&s1), calculate_corpora_fingerprint(&s2));

=======
>>>>>>> master
        let s3 = vec![CorpusSource {
            id: "a".into(),
            weight: 1.0,
            hash: None,
        }];
<<<<<<< HEAD
        assert_ne!(calculate_corpora_fingerprint(&s1), calculate_corpora_fingerprint(&s3));
    }

    #[test]
    fn test_job_id_from_parts() {
        let geo = KeyboardGeometry::default();
        let weights = ScoringWeights::default();
        let params = SearchParams::default();

        let id = JobIdentifier::from_parts(
            &geo,
            &weights,
            &params,
            &[],
            "en",
            &CostMatrixSource::default(),
        );
        assert!(id.is_ok());
=======
        assert_ne!(calculate_corpora_hash(&s1), calculate_corpora_hash(&s3));
        Ok(())
>>>>>>> master
    }
}
