// libs/keyforge-model/src/job.rs

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Job identification and hashing logic.
//!
//! This module provides the `JobIdentifier` used to uniquely identify
//! a specific optimization task based on its configuration.

use crate::config::{CostMatrixSource, KeyConstraint, ScoringWeights, SearchParams};
use crate::geometry::KeyboardGeometry;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use utoipa::ToSchema;

use crate::config::CorpusSource;

/// Generates a deterministic hash for a set of corpora sources, incorporating content hashes if present.
#[must_use]
pub fn calculate_corpora_hash(sources: &[CorpusSource]) -> String {
    // 1. Sort by ID for canonicalization
    let mut sorted = sources.to_vec();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));

    // 2. Hash the sorted list deterministically
    let mut hasher = Sha256::new();
    for s in &sorted {
        hasher.update(s.id.as_bytes());
        // Use separator to prevent concatenation collisions
        hasher.update([0xFF]);

        // Hash weight bits for strict equality
        hasher.update(s.weight.to_bits().to_be_bytes());
        hasher.update([0xFF]);

        // Incorporate hash field if present
        if let Some(h) = &s.hash {
            hasher.update([0x01]); // Marker for Some
            hasher.update(h.as_bytes());
        } else {
            hasher.update([0x00]); // Marker for None
        }
        hasher.update([0xFF]); // End of item separator
    }

    hex::encode(hasher.finalize())
}

/// Unique identifier for a specific optimization job configuration.
/// Generated by hashing the canonical representation of all inputs.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, PartialEq, Eq)]
pub struct JobIdentifier {
    /// The hex-encoded SHA-256 hash.
    pub hash: String,
}

/// Marker trait for Job states.
pub trait JobState: std::fmt::Debug + Clone + Serialize {}

/// Job is in the queue, awaiting a worker.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]

pub struct Pending;
impl JobState for Pending {}

/// Job is currently being processed by one or more workers.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]

pub struct Running {
    /// Number of active worker nodes.
    pub active_nodes: usize,
    /// Best score found so far.
    pub current_best: Option<crate::types::Score>,
}
impl JobState for Running {}

/// Job has been finished or timed out.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]

pub struct Completed {
    /// Final best score achieved.
    pub final_score: crate::types::Score,
    /// Final optimized layout.
    pub final_layout: crate::layout::Layout,
    /// Total compute time across all nodes (seconds).
    pub total_compute_sec: u64,
}
impl JobState for Completed {}

/// A reified Optimization Job, following the Typestate Pattern.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Job<S: JobState> {
    /// Canonical identifier.
    pub id: JobIdentifier,
    /// Current state data.
    pub state: S,
}

/// Unified Enum for Job Status (used in protocols and persistence).
///
/// # Examples
///
/// ```
/// use keyforge_model::{JobStatus, Running, Score};
/// let status = JobStatus::Running(Running {
///     active_nodes: 5,
///     current_best: Some(Score::from_scaled_i64(100)),
/// });
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum JobStatus {
    /// Job is awaiting workers.
    Pending(Pending),
    /// Job is active.
    Running(Running),
    /// Job is finished.
    Completed(Completed),
}

use crate::error::ModelError;

impl JobIdentifier {
    /// Attempts to generate a Job ID from the constituent parts.
    ///
    /// # Errors
    ///
    /// Returns a `ModelError` if any of the parts cannot be serialized or
    /// if the configuration is invalid.
    pub fn try_from_parts(
        geometry: &KeyboardGeometry,
        weights: &ScoringWeights,
        params: &SearchParams,
        pinned_keys: &[KeyConstraint],
        corpora_hash: &str,
        cost_matrix: &CostMatrixSource,
        cost_matrix_hash: Option<&str>,
    ) -> Result<Self, ModelError> {
        fn feed<T: Serialize>(hasher: &mut Sha256, value: &T) -> Result<(), ModelError> {
            // Use serde_json::to_value -> to_vec for deterministic canonicalization.
            // to_value converts structs/maps to a BTreeMap-backed Value, ensuring sorted keys.
            let canonical = serde_json::to_value(value)
                .map_err(|e| ModelError::Serialization(e.to_string()))?;

            let bytes = serde_json::to_vec(&canonical)
                .map_err(|e| ModelError::Serialization(e.to_string()))?;

            hasher.update((bytes.len() as u64).to_le_bytes());
            hasher.update(&bytes);
            Ok(())
        }

        let mut hasher = Sha256::new();

        feed(&mut hasher, geometry)?;
        feed(&mut hasher, weights)?;
        feed(&mut hasher, params)?;

        // Sort pins for canonicalization
        let mut sorted_pins = pinned_keys.to_vec();
        sorted_pins.sort_by(|a, b| a.index.cmp(&b.index));
        feed(&mut hasher, &sorted_pins)?;

        hasher.update((corpora_hash.len() as u64).to_le_bytes());
        hasher.update(corpora_hash.as_bytes());

        match cost_matrix {
            CostMatrixSource::Predefined(s) => {
                hasher.update(b"PRE");
                hasher.update(s.as_bytes());
                if let Some(h) = cost_matrix_hash {
                    hasher.update(b"H:");
                    hasher.update(h.as_bytes());
                }
            }
        }

        let result = hasher.finalize();
        Ok(Self {
            hash: hex::encode(result),
        })
    }

    /// Generates a Job ID, returning a Result.
    /// This replaces the panicking `from_parts` method.
    ///
    /// # Errors
    ///
    /// Returns a `ModelError` if any of the constituent parts fail validation
    /// or serialization.
    pub fn from_parts(
        geometry: &KeyboardGeometry,
        weights: &ScoringWeights,
        params: &SearchParams,
        pinned_keys: &[KeyConstraint],
        corpora_hash: &str,
        cost_matrix: &CostMatrixSource,
        cost_matrix_hash: Option<&str>,
    ) -> Result<Self, ModelError> {
        Self::try_from_parts(
            geometry,
            weights,
            params,
            pinned_keys,
            corpora_hash,
            cost_matrix,
            cost_matrix_hash,
        )
    }
}

#[keyforge_testing_macros::kf_test]
mod tests {
    use super::*;
    use crate::types::KeyIndex;

    #[test]
    fn test_job_id_determinism() {
        let geo = KeyboardGeometry::default();
        let weights = ScoringWeights::default();
        let params = SearchParams::default();
        let pins = vec![KeyConstraint {
            index: KeyIndex::new(0),
            key: "A".into(),
        }];

        let id1 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &pins,
            "en",
            &CostMatrixSource::default(),
            None,
        )
        .unwrap();
        let id2 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &pins,
            "en",
            &CostMatrixSource::default(),
            None,
        )
        .unwrap();

        assert_eq!(id1.hash, id2.hash);
    }

    #[test]
    fn test_job_id_pin_sorting_determinism() {
        let geo = KeyboardGeometry::default();
        let weights = ScoringWeights::default();
        let params = SearchParams::default();

        let pin_a = KeyConstraint {
            index: KeyIndex::new(0),
            key: "A".into(),
        };
        let pin_b = KeyConstraint {
            index: KeyIndex::new(1),
            key: "B".into(),
        };

        let id1 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &[pin_a.clone(), pin_b.clone()],
            "en",
            &CostMatrixSource::default(),
            None,
        )
        .unwrap();
        let id2 = JobIdentifier::try_from_parts(
            &geo,
            &weights,
            &params,
            &[pin_b, pin_a],
            "en",
            &CostMatrixSource::default(),
            None,
        )
        .unwrap();

        assert_eq!(
            id1.hash, id2.hash,
            "Hash must be same regardless of pin order"
        );
    }

    #[test]
    fn test_calculate_corpora_hash_content_addressing() {
        let s1 = vec![CorpusSource {
            id: "a".into(),
            weight: 1.0,
            hash: Some("hash1".into()),
        }];
        let s2 = vec![CorpusSource {
            id: "a".into(),
            weight: 1.0,
            hash: Some("hash2".into()),
        }];
        assert_ne!(calculate_corpora_hash(&s1), calculate_corpora_hash(&s2));

        let s3 = vec![CorpusSource {
            id: "a".into(),
            weight: 1.0,
            hash: None,
        }];
        assert_ne!(calculate_corpora_hash(&s1), calculate_corpora_hash(&s3));
    }

    #[test]
    fn test_job_id_from_parts() {
        let geo = KeyboardGeometry::default();
        let weights = ScoringWeights::default();
        let params = SearchParams::default();

        let id = JobIdentifier::from_parts(
            &geo,
            &weights,
            &params,
            &[],
            "en",
            &CostMatrixSource::default(),
            None,
        );
        assert!(id.is_ok());
    }
}
