[package]
name = "keyforge-evolution"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description = "Evolutionary optimization algorithms and search strategies for generating keyboard layouts."
repository.workspace = true
[lints]
workspace = true

[dependencies]
keyforge-testing-macros.workspace = true
rand.workspace = true
rand_xoshiro.workspace = true
serde.workspace = true
keyforge-model = { path = "../keyforge-model" }
keyforge-physics = { path = "../keyforge-physics" }
tracing.workspace = true
thiserror.workspace = true
keyforge-protocol = { path = "../keyforge-protocol" }

[features]
default = []
single_threaded = []

[dev-dependencies]
keyforge-protocol = { path = "../keyforge-protocol" }
proptest.workspace = true
serde_json.workspace = true
anyhow.workspace = true
keyforge-model = { path = "../keyforge-model", features = ["testing"] }
