[package]
name = "openbookcorpus"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description = "Specialized corpus management and data processing for the Open Book project dataset."
repository.workspace = true
[lints]
workspace = true

[dependencies]
# ADD "json" HERE:
reqwest.workspace = true
tokio.workspace = true
futures-util.workspace = true
indicatif.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt"] }

# Processing dependencies
parquet.workspace = true
serde.workspace = true
serde_json.workspace = true
regex.workspace = true
rayon.workspace = true
rustc-hash.workspace = true
keyforge-testing-macros.workspace = true

[dev-dependencies]
keyforge-testing = { path = "../../libs/keyforge-testing" }
tempfile.workspace = true
